foreground #ff22ff
background #100040

background_opacity 0.2

background_image ./kitty-bg2.png
background_image_layout clamped
background_tint 0.9

font_size 17.0

font_family family="Adwaita Mono"

foreground         #ff22ff
background         #100040
background_opacity 0.2
background_image   ./kitty-bg2.png
background_image_layout clamped
background_tint    0.9

font_size          17.0
font_family        family="Adwaita Mono"

